version: '3'

services:
  server:
    image: ${ECR_REGISTRY_URL}/wanted_server_prac/latest
    ports:
      - '80:3032'
    restart: always
    env_file:
      - ./.env

  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3010:3306'
